### ISSUE TITLE
根据提示操作后，没有弹出结果，也没有报错

### ISSUE THREAD

**Issue by tangxueming** [xkerwin/Scriptbale#4]
1.ios 14， scriptable 测试版（正式版也试过），iphone 7s，代码版本b69305b13d2f3548d85af1053dc154b45683f444，增加了几个节日提醒！

2.运行流程
（1） 执行
（2）选背景截图，继续（已有截图）
（3）部件尺寸，Small
（4）位置 ，Top Left
（5） 在scriptable中使用还是导出图像。 
i.导出图像，结果是根据尺寸截取的背景图
ii. 在scriptable中使用，程序运行结束，没响应。
谢谢

**Comment by smallfish01** [comment]
需要在手机上滑动到最左边，按住屏幕空白处进入编辑状态，添加小组件，然后添加即可。

**Comment by tangxueming** [comment]
> 需要在手机上滑动到最左边，按住屏幕空白处进入编辑状态，添加小组件，然后添加即可。

谢谢！
 小组件添加后， 还要点击小组件做配置，（1.选脚本，2.交互选运行脚本）
以前没玩过，昨天没做配置。

**Comment by tangxueming** [comment]
已解决
